hackernewscore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('topnews.urls', namespace='topnews')),
    path('api/', include('topnews_api.urls', namespace='topnews_api')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

topnews/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'topnews'
urlpatterns = [
    path('', views.home, name='home'),
    path('comments/', views.comments, name='comments'),
    path('jobs/', views.jobs, name='jobs'),
    path('detail/<int:pk>/', views.story_detail, name='story_detail'),
    path('search/', views.search, name='search')
]

topnews_api/urls.py
from django.urls import path
from .views import CommentDetail, StoryList, StoryDetail, JobList, CommentList, CreateComment

app_name = 'topnews_api'
urlpatterns = [
    path('', StoryList.as_view(), name='itemlist'),
    path('storydetail/<int:story_id>/', StoryDetail.as_view(),name='storydetail'),
    path('jobs/', JobList.as_view(), name='joblist'),
    path('comments/', CommentList.as_view(), name='commentlist'),
    path('commentdetail/<int:id>/', CommentDetail.as_view(), name='commentdetail'),
    path('createcomment/', CreateComment.as_view(), name='createcomment')
]

topnews/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.utils import timezone
from django.shortcuts import reverse

# Create your models here.

NEWS_TYPE = (
    ('job', 'job'),
    ('story', 'story'),
    ('comment', 'comment'),
    ('poll', 'poll'),
    ('pollopt', 'pollopt'),
)


class Story(models.Model):
    author = models.CharField(max_length=50, null=True,
                              blank=True, default='Anonymous')
    title = models.CharField(max_length=200, null=True, blank=True)
    story_link = models.URLField(max_length=200, null=True, blank=True)
    slug = models.SlugField(max_length=255)
    item_type = models.CharField(
        max_length=30, choices=NEWS_TYPE, default='story')
    created = models.DateTimeField(blank=True, default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('topnews:story_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    story_id = models.ForeignKey(
        Story, on_delete=models.CASCADE, null=True, blank=True)
    commenter = models.CharField(max_length=50, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    item_type = models.CharField(
        max_length=30, choices=NEWS_TYPE, default='comment')
    created = models.DateTimeField(blank=True, default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.commenter


class Job(models.Model):
    job_poster = models.CharField(
        max_length=50, null=True, default='Anonymous')
    job_title = models.CharField(max_length=200, null=True)
    item_type = models.CharField(
        max_length=50, choices=NEWS_TYPE, default='job')
    job_link = models.URLField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(blank=True, default=timezone.now)
    

    def __str__(self):
        return self.job_title

topnews/views.py
from multiprocessing import context
from unittest import result
from urllib import request
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Story, Comment, Job
from django.db.models import Q
# Create your views here.

def home(request):
    topstories = Story.objects.all().order_by('-created')
    
    page = request.GET.get('page', 1)
    paginator = Paginator(topstories, 10)
    try:
        mystories = paginator.page(page)
    except PageNotAnInteger:
        mystories = paginator.page(1)
    except EmptyPage:
        mystories = paginator.page(paginator.num_pages)

    context = {"topstories":mystories, "totalstories":topstories.count()}
    return render(request, 'topnews/home.html', context)


def jobs(request):
    my_jobs = Job.objects.all().order_by('-created')
    page = request.GET.get('page', 1)
    paginator = Paginator(my_jobs, 15)
    try:
        myjobs = paginator.page(page)
    except PageNotAnInteger:
        myjobs = paginator.page(1)
    except EmptyPage:
        myjobs = paginator.page(paginator.num_pages)

    context= {"my_jobs":myjobs, 'total_jobs':my_jobs.count()}
    return render(request, 'topnews/jobs.html', context)

def comments(request):
    topcomments = Comment.objects.select_related('story_id').all()
    page = request.GET.get('page', 1)
    paginator = Paginator(topcomments, 65)
    try:
        my_comments = paginator.page(page)
    except PageNotAnInteger:
        my_comments = paginator.page(1)
    except EmptyPage:
        my_comments = paginator.page(paginator.num_pages)
    
    context = {"topcomments":my_comments, "total_comments":topcomments.count()}
    return render(request, 'topnews/comments.html', context)


def story_detail(request, pk):
    story = get_object_or_404(Story, pk=pk)
    story_comments = Comment.objects.filter(story_id=pk).order_by('-created')

    context = {"story":story, "story_comments":story_comments}
    return render(request, 'topnews/storydetail.html', context=context)


          
def search(request):
    context = {}
    
    search = request.GET.get('search')
    results = Job.objects.filter(Q(
            job_title__icontains=search)).order_by('-created')
    if search in results:

        page = request.GET.get('page', 1)
        paginator = Paginator(results, 15)
        try:
            job_results = paginator.page(page)
        except PageNotAnInteger:
            job_results = paginator.page(1)
        except EmptyPage:
            job_results = paginator.page(paginator.num_pages)

        context['results'] = results
        context['job_results'] = job_results
        context['total_jobs'] = results.count()
        return render(request, 'topnews/job.html', context)
        
    else:
        stories = Story.objects.filter(Q(author__icontains=search) | Q(
            item_type__icontains=search) | Q(title__icontains=search)).order_by('-created')
        page = request.GET.get('page', 1)
        paginator = Paginator(stories, 15)
        try:
            story_results = paginator.page(page)
        except PageNotAnInteger:
            story_results = paginator.page(1)
        except EmptyPage:
            story_results = paginator.page(paginator.num_pages)

    
    context['story_results'] = story_results
    context['stories'] = stories
    
    
    return render(request, 'topnews/search.html', context)




                
                # page = request.GET.get('page', 1)
                # paginator = Paginator(stories, 15)
                # try:
                #     story_results = paginator.page(page)
                # except PageNotAnInteger:
                #     story_results = paginator.page(1)
                # except EmptyPage:
                #     story_results = paginator.page(paginator.num_pages)

         
   
        
            

templates/topnews/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}Book Store{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
              <a href="{% url 'topnews:home' %}" class="navbar-brand" style=" font-weight: bold;">HACKERNEWS</a>
              <form method="GET" action="{% url 'topnews:search' %}" class="d-flex" style="width:500px !important;">
                
                <input class="form-control me-" type="text" name="search" placeholder="Story author, Story Title..." aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </nav>
    </header>
    <div class="container">
        <div class="alert alert-primary fw600 rounded-0 border-0 py-3" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-info-circle me-2"
              viewBox="0 0 16 16">
              <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
              <path
                d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
            </svg>
            COVID-19 - <a target="_blank" href="https://covid19.ncdc.gov.ng/">Click here for our latest updates</a> on our stores, website and contact centre. Thank you for
            your patience and support.
          </div>

    </div>
    <div class="container">
      <span><i class="fa fa-filter"></i></span>
      <a class='btn btn-light' href="{% url 'topnews:home' %}">Story</a>
      <a class='btn btn-light' href="{% url 'topnews:jobs' %}">Job</a>
      <a class='btn btn-light' href="{% url 'topnews:comments' %}">Comments</a>
  
  </div>
    <div id="content">{% block content %} {% endblock %}</div>
    
    
</body>
</html>

templates/topnews/comments.html
{% extends 'topnews/base.html' %}
{% block title %}Comments{% endblock %}
{% block content %}
{% if total_comments > 0 %}
{% for comment in topcomments %}
<div class="container p-2">
    <div class="list-group">
        <a href="{% url 'topnews_api:commentdetail' comment.id %}" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ comment.comment }}</h5>
            <small>Posted by {{ comment.commenter }} {{ comment.created }}</small>
          </div>
        </a>
       
      </div>

</div>
{% endfor %}

{% else %}
    <p> There are no available comments </p>
{% endif %}
<div class="container">
  {% if topcomments.has_other_pages %}
           <nav aria-label="Page navigation example">
               <ul class="pagination">
                   {% if topcomments.has_previous %}
                     <li class="page-item"><a class="page-link" href="?page={{ topcomments.previous_page_number }}" aria-label="Previous">
                         <span aria-hidden="true" >&laquo;</span>
                         <span class="sr-only">Previous</span>
                         </a>
                     </li>
                   {% else %}
                     <li class=" page-item disabled page-link"><span>&laquo;</span></li>
                   {% endif %}
                   {% for i in topcomments.paginator.page_range %}
                     {% if topcomments == i %}
                         <li class="active page-item page-link mr-5 text-end"><span style="color: lightblue;">{{ i }} <span class="sr-only">(current)</span></span></li>
                     {% else %}
                         <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                     {% endif %}
                   {% endfor %}
                   {% if topcomments.has_next %}
                     <li class="page-item"><a class="page-link" href="?page={{ topcomments.next_page_number }}" aria-label="Next">
                         <span aria-hidden="true" >&raquo;</span>
                         <span class="sr-only">Next</span>
                         </a>
                     </li>
                   {% else %}
                     <li class=" page-item disabled page-link"><span>&raquo;</span></li>
                   {% endif %}
               </ul>
           </nav>
           {% endif %}

</div>
{% endblock %}

templates/topnews/home.html
{% extends 'topnews/base.html' %}
{% block title %}HackerNews{% endblock %}

{% block content %}
{% if totalstories > 0 %}
{% for topstory in topstories %}
<div class="container p-2">
    <div class="list-group">
        <a href="{{ topstory.get_absolute_url }}" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ topstory.title }}</h5>
            <small>Posted by {{ topstory.author }} at {{ topstory.created }}</small>
          </div>
          <p class="mb-1">{{ topstory.story_link}}</p>
          <small>{{ topstory.comment }}</small>
        </a>
    </div>
</div>
{% endfor %}


{% else %}
    <p> There are no available stories </p>
{% endif %}
<div class="container">
   {% if topstories.has_other_pages %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if topstories.has_previous %}
                      <li class="page-item"><a class="page-link" href="?page={{ topstories.previous_page_number }}" aria-label="Previous">
                          <span aria-hidden="true" >&laquo;</span>
                          <span class="sr-only">Previous</span>
                          </a>
                      </li>
                    {% else %}
                      <li class=" page-item disabled page-link"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in topstories.paginator.page_range %}
                      {% if topstories.number == i %}
                          <li class="active page-item page-link mr-5 text-end"><span style="color: lightblue;">{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if topstories.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ topstories.next_page_number }}" aria-label="Next">
                          <span aria-hidden="true" >&raquo;</span>
                          <span class="sr-only">Next</span>
                          </a>
                      </li>
                    {% else %}
                      <li class=" page-item disabled page-link"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}

</div>
   
{% endblock %}

templates/topnews/jobs.html
{% extends 'topnews/base.html' %}
{% block title %}Jobs{% endblock %}
{% block content %}
{% if total_jobs > 0 %}
{% for job in my_jobs %}
<div class="container p-2">
    <div class="list-group">
        <a href="" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ job.job_title }}</h5>
            <small>Posted by {{ job.job_poster }} at {{ job.created }}</small>
          </div>
          
        </a>
    </div>
</div>
{% endfor %}
{% else %}
<p class="container">No available jobs</p>
{% endif %}
{% endblock %}

templates/topnews/search.html
{% extends 'topnews/base.html' %}
{% block content %}
{% for text in stories %}
<div class="container p-2">
    <div class="list-group">
        <a href="{{ text.get_absolute_url }}" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ text.title }}</h5>
            <small>Posted by {{ text.author }} at {{ text.created }}</small>
          </div>
          
        </a>
    </div>
</div>
{% endfor %}

{% for job in results %}
<div class="container p-2">
    <div class="list-group">
        <a href="" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ job.job_title }}</h5>
            <small>Posted by {{ job.job_poster }} at {{ job.created }}</small>
          </div>
          
        </a>
    </div>
</div>

{% endfor %}
{% endblock %}

templates/topnews/storydetail.html
{% extends 'topnews/base.html' %}
{% block title %}{{ story|title }}{% endblock %}
{% block content %}
<div class="container p-2">
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-center">
            <h5 class="mb-1">>Author : {{story.author|title}}</h5>
            <p class="lead">{{ story.title }}</p>
            <hr class="my-4">
            <p>{{ story.story_link }}</p>
            <p class="lead">
              <a href="{% url 'topnews_api:createcomment' %}" class="btn btn-primary btn-sm mt-3" role="button" style="color: white;">Add comment</a>
            </p>
          </div>
        </a>
       
      </div>
      {% for comment in story_comments %}
      <div class="colist-group pt-2">
      <a href="{% url 'topnews_api:commentdetail' comment.id %}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Comment: {{ comment.comment }}</h5>
          <small>commenter: {{ comment.commenter }}</small>
        </div>
      </a>

      
       
         

      </div>
      
    
      <hr class="my-4">
      {% endfor %}
{% endblock %}